name: Test

on:
  push:
    branches: ['denkiyagi-fork']
  pull_request:
    branches: ['denkiyagi-fork']

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@denkiyagi'
          cache: yarn

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test
